[#ftl]
[@b.head/]
[@b.toolbar title="上传教学大纲"]bar.addBack();[/@]
  [#assign sa][#if syllabus.persisted]!update?id=${syllabus.id}[#else]!save[/#if][/#assign]
    [@b.form action=sa theme="list"  enctype="multipart/form-data"]
      [@b.select name="syllabus.course.id" label="选择课程" items=courses value = syllabus.course empty="..."/]
      [@b.select name="syllabus.locale" label="语言" items=localeList option="language,language" value = syllabus.locale empty="..." disabled=true/]
      [@b.field label="上传教学大纲"]
      <input name="attachment" type="file"/>
      [/@]
      [#if syllabus.persisted]
      [@b.field label="已有大纲版本"]
      [#list syllabus.revisions! as revision]
        ${revision.updatedAt?string("yyyy-MM-dd HH:mm")!}
        [#if revision.attachment??]
          [@b.a target="_blank" href="!attachment?revisionId=${revision.id}"]
            ${(revision.attachment.name)!}
          [/@]
        [/#if]
        <#sep><br/></#sep>
      [/#list]
      [/@]
      [/#if]
      [@b.formfoot]
        [#if syllabus.persisted]<input type="hidden" name="syllabus.id" value="${syllabus.id!}" />[/#if]
        [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
      [/@]
    [/@]
[@b.foot/]